[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  changeFreq = "daily"
  exclude = [
    # By file Path
    './PPPub/**',
    './vscode/**',
    './test**',
    './_development/**',
    './thankyou.html',
    './google**',
    # By Glob pattern
    #'**/**/child-one.html'
  ]
  filePath = "./sitemap.xml"
